### ISSUE TITLE
Type error

### ISSUE THREAD

**Issue by Bryan-Wong919** [a1600012888/PhysDreamer#5]
Hi, first i want to thank you for this excellent work! However, i come up with this error while run the "demo.py"
The error is:
Traceback (most recent call last):
  File "demo.py", line 42, in <module>
    from physdreamer.warp_mpm.mpm_solver_diff import MPMWARPDiff
  File "/home/swu/wzy/PhysDreamer/physdreamer/warp_mpm/mpm_solver_diff.py", line 13, in <module>
    class MPMWARPDiff(object):
  File "/home/swu/wzy/PhysDreamer/physdreamer/warp_mpm/mpm_solver_diff.py", line 144, in MPMWARPDiff
    E: Float[Tensor, "n"] | Float[Tensor, "1"],
TypeError: unsupported operand type(s) for |: 'MetaAbstractArray' and 'MetaAbstractArray'

can you tell how to solve it?
thanks!

**Comment by a1600012888** [comment]
Hi, 

This seems a problem with typing. I used `Float[Tensor, "n"] | Float[Tensor, "1"],` in the annotations : https://github.com/a1600012888/PhysDreamer/blob/main/physdreamer/warp_mpm/mpm_solver_diff.py#L144,  
and you package version doesn't support it. 

What's your jaxtyping, typing and python version?  

I used jaxtyping==0.2.28 with  python as 3.10.12. 

A easy fix would be to align the versions, or simply remove the annotations at above mentioned lines.

**Comment by Bryan-Wong919** [comment]
Hi, 
Thanks for the reply. My jaxtyping version is 0.2.19 and my python version is 3.8.19. I will try the version you recommend.
